/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    LangSelect: typeof import('./../src/components/lang-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSelector: typeof import('./../src/components/theme-selector/index.vue')['default']
    ThemeSewitcher: typeof import('./../src/components/theme-sewitcher/index.vue')['default']
    ThemeSwitcher: typeof import('./../src/components/theme-switcher/index.vue')['default']
  }
}
